[tool.poetry]
name = "frc-docs"
version = "9999"
description = ""
authors = []

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
doc8 = "==0.11.1"
docutils = "==0.17.0"
fonttools = {version = "==4.33.3", extras = ["woff"]}
jsmin = "==3.0.0"
latex = "==0.7.0"
packaging = "==20.9"
scipy = ">=1.9.0, <2.0.0"
sphinx = "==4.5.0"
sphinx-hoverxref = "==1.0.1"
sphinx-notfound-page = "==0.8.0"
sphinx-panels = "==0.6.0"
sphinx-rtd-theme = "==1.0.0"
sphinx-tabs = "==3.3.1"
sphinx-toolbox = "==3.1.0"
sphinx-version-warning = "==1.1.2"
sphinxcontrib-ghcontributors = "==0.2.3"
sphinxcontrib-htmlhelp = "==2.0.0"
sphinxcontrib-serializinghtml = "==1.1.5"
sphinxcontrib-svg2pdfconverter = "==1.2.0"
sphinxext-delta = "==0.2.0"
sphinxext-linkcheckdiff = "==0.1.0"
sphinxext-mimic = "==0.1.1"
sphinxext-opengraph = "==0.4.1"
sphinxext-photofinish = "==0.1.9"
sphinxext-presentations = "==0.2.2"
sphinxext-rediraffe = "==0.2.5"
sphinxext-remoteliteralinclude = "==0.3.0"
sphinxext-toptranslators = "==0.1.2"
urllib3 = ">=1.26.6, <2.0.0"
frccontrol = "==2022.14"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
