[tool.poetry]
name = "frc-docs"
version = "9999"
description = ""
authors = []

[tool.poetry.dependencies]
doc8 = "==0.8.1"
docutils = "==0.16.0"
latex = "==0.7.0"
python = "^3.6"
sphinx = "==4.1.1"
sphinx-hoverxref = "==0.7b1"
sphinx-notfound-page = "==0.7.1"
sphinx-panels = "==0.6.0"
sphinx-rtd-theme = "==1.0.0"
sphinx-tabs = "==3.2.0"
sphinx-version-warning = "==1.1.2"
sphinxcontrib-ghcontributors = "==0.2.2"
sphinxcontrib-htmlhelp = "==2.0.0"
sphinxcontrib-serializinghtml = "==1.1.5"
sphinxcontrib-svg2pdfconverter = "==1.1.1"
sphinxext-delta = "==0.1.0"
sphinxext-linkcheckdiff = "==0.1.0"
sphinxext-mimic = "==0.1.1"
sphinxext-opengraph = "==0.4.1"
sphinxext-rediraffe = "==0.2.5"
sphinxext-remoteliteralinclude = "==0.3.0"
sphinxext-toptranslators = "==0.1.2"
urllib3 = ">=1.26.6, <2.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
