name: CI

on: [pull_request, push]

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'pip'
    - name: Install Python Dependencies
      run: |
        pip install -r source/requirements.txt
    - name: Install LaTeX
      run: |
        sudo apt-fast -y update
        sudo apt-fast install -y texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra latexmk texlive-lang-greek texlive-luatex texlive-xetex texlive-fonts-extra dvipng librsvg2-bin
    - name: Build PDF
      run: |
        make latexpdf
    - name: Archive PDF
      uses: actions/upload-artifact@v2
      with:
        name: frc-docs-pdf
        path: build/latex/firstroboticscompetition.pdf
        if-no-files-found: error
        
  build-html:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'pip'
    - name: Install Python Dependencies
      run: |
        pip install -r source/requirements.txt
    - name: Install librsvg2
      run: |
        sudo apt-fast -y update
        sudo apt-fast install -y librsvg2-bin
    - name: Build HTML
      run: |
        make html
    - name: Archive HTML
      uses: actions/upload-artifact@v2
      with:
        name: frc-docs-html
        path: build/html/
        if-no-files-found: error
        
  build-html-translation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: wpilibsuite/frc-docs-translations
    - name: Delete old submodule
      run: |
        rm -rf ./frc-docs
    - uses: actions/checkout@v3
      with:
        path: frc-docs
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'pip'
    - name: Install Python Dependencies
      run: |
        pip install -r frc-docs/source/requirements.txt
    - name: Install librsvg2
      run: |
        sudo apt-fast -y update
        sudo apt-fast install -y librsvg2-bin
    - name: Build HTML
      run: |
        sphinx-build -D language=es -b html . _build/html

  check-links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: main
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        pip install -r source/requirements.txt
    - name: Check Links
      run: |
        make linkcheck
        
  check-linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        pip install -r source/requirements.txt
    - name: Check Lint
      run: |
        make lint
        
  check-image-size:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        pip install -r source/requirements.txt
    - name: Check Image Size
      run: |
        make sizecheck
        
  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          locale: "US"
          reporter: "github-check"
          
  check-redirects:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout main
      run: |
        git fetch origin main --depth=1
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        pip install -r source/requirements.txt
    - name: Check redirects
      run: |
        make rediraffecheckdiff
    - name: Check redirects format
      run: |
        [[ $(<source/redirects.txt) == $(git show origin/main:source/redirects.txt)* ]] || { echo "Error: redirects.txt can only be appended to. Lines cannot be modified or deleted."; exit 1; }
        
  check-formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - uses: psf/black@22.1.0
      with:
        black_args: ". --check"
